CREATE ROLE "keycloak" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'keycloak';
CREATE DATABASE keycloak owner "keycloak" encoding "utf-8";
GRANT ALL PRIVILEGES ON DATABASE keycloak TO "keycloak";
GRANT ALL PRIVILEGES ON SCHEMA "public" TO "keycloak";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "keycloak";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO "keycloak";
