CREATE TABLE IF NOT EXISTS operators (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    rank VARCHAR(255) NOT NULL,
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS computers (
    uuid_label INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    host_name VARCHAR(255) UNIQUE NOT NULL,
    mac_address VARCHAR(255) UNIQUE NOT NULL,
    ipv4_address VARCHAR(255),
    network VARCHAR(255) NOT NULL,
    os VARCHAR(255) NOT NULL,
    network_adapter VARCHAR(255) NOT NULL,
    secseal INTEGER UNIQUE NOT NULL,
    make VARCHAR(255),
    model VARCHAR(255),
    pc_serialnumber VARCHAR(255),
    net_adapter_serialnumber VARCHAR(255),
    user_name VARCHAR(255),
    yat VARCHAR(255),
    office_number VARCHAR(255),
    telephone VARCHAR(255),
    office_location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS entries (
    uuid INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    uuid_label INTEGER NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Athens'),
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'open',
    signed_by VARCHAR(255),
    signed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_label FOREIGN KEY (uuid_label) REFERENCES computers(uuid_label) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Athens'),
    priority VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'open',
    division VARCHAR(255),
    office_number VARCHAR(255),
    phone VARCHAR(255),
    client_name VARCHAR(255),
    descr VARCHAR(2048),
    title VARCHAR(255) NOT NULL
);
